name: Build Apk z
on: 
 workflow_dispatch:
  inputs:
   retentionDays:
   description: "The number of days to retain the apk."
   required: true
   default: "10"
   
   
jobs:
  main:
    runs-on: ubuntu-latest
    steps:

        

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ github.event.inputs.jdkVersion }}

          
      - name: build
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace

 
      - name: Upload the APK artifact 
        uses: actions/upload-artifact@v4
        with:
          name: apk-archive
          path: ./**/*.apk
          retention-days: ${{ github.event.inputs.retentionDays }}

 

        
 
